### ISSUE TITLE
SerialResponseTransport.handleSerialTimeout  nachdem das Programm schon gelaufen ist

### ISSUE THREAD

**Issue by stallingerl** [webanizer/Consolino2IPFS#18]
Vermutlich async error

SerialResponseTransport.handleSerialTimeout 

Error: No or too long answer from Serial Device after last request.
    at SerialResponseTransport.handleSerialTimeout (/home/Consolino2IPFS/node_modules/smartmeter-obis/lib/transports/SerialResponseTransport.js:292:36)
    at Timeout._onTimeout (/home/Consolino2IPFS/node_modules/smartmeter-obis/lib/transports/SerialResponseTransport.js:245:18)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockckpro@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockckpro@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by davidreband** [comment]
Das Problem ist gelöst,
ein paar Bugs entfernt,
settings eingerichtet
